//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoQuiz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntityContainer : DbContext
    {
        public DBEntityContainer()
            : base("name=DBEntityContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<QZ_GetAllSectionsQuestionsForVideoQuiz_Result> QZ_GetAllSectionsQuestionsForVideoQuiz(Nullable<int> quizID)
        {
            var quizIDParameter = quizID.HasValue ?
                new ObjectParameter("quizID", quizID) :
                new ObjectParameter("quizID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QZ_GetAllSectionsQuestionsForVideoQuiz_Result>("QZ_GetAllSectionsQuestionsForVideoQuiz", quizIDParameter);
        }
    
        public virtual ObjectResult<QZ_GetAnswer_MCH_Result> QZ_GetAnswer_MCH(Nullable<int> questionID)
        {
            var questionIDParameter = questionID.HasValue ?
                new ObjectParameter("questionID", questionID) :
                new ObjectParameter("questionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QZ_GetAnswer_MCH_Result>("QZ_GetAnswer_MCH", questionIDParameter);
        }
    
        public virtual ObjectResult<QZ_Video_GetCuepointsByQuizId_Result> QZ_Video_GetCuepointsByQuizId(Nullable<int> quizID)
        {
            var quizIDParameter = quizID.HasValue ?
                new ObjectParameter("quizID", quizID) :
                new ObjectParameter("quizID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QZ_Video_GetCuepointsByQuizId_Result>("QZ_Video_GetCuepointsByQuizId", quizIDParameter);
        }
    }
}
