//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoQuiz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntityContainer : DbContext
    {
        public DBEntityContainer()
            : base("name=DBEntityContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<QZVideoQuizAttachement> QZVideoQuizAttachement { get; set; }
        public virtual DbSet<LOResource> LOResource { get; set; }
        public virtual DbSet<QZResult> QZResult { get; set; }
        public virtual DbSet<QZQuiz> QZQuiz { get; set; }
        public virtual DbSet<QZQuestion> QZQuestion { get; set; }
        public virtual DbSet<QZSection> QZSection { get; set; }
        public virtual DbSet<QZAnswer_MCH> QZAnswer_MCH { get; set; }
        public virtual DbSet<QZVideoQuizQuePoint> QZVideoQuizQuePoint { get; set; }
    }
}
