//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOResource
    {
        public int ID { get; set; }
        public Nullable<int> VirtualFolderID { get; set; }
        public Nullable<System.Guid> FilePhysicalFolderFUID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ContentType { get; set; }
        public string ToolType { get; set; }
        public string Url { get; set; }
        public string FileUploadType { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FileMimeType { get; set; }
        public string Filesize { get; set; }
        public Nullable<System.Guid> CreatedByPUID { get; set; }
        public Nullable<System.Guid> ModifidedByPUID { get; set; }
        public Nullable<System.DateTime> DateTimeCreated { get; set; }
        public Nullable<System.DateTime> DateTimeModified { get; set; }
    }
}
