//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QZAnswer_MCH
    {
        public int ID { get; set; }
        public int QuestionID { get; set; }
        public string AnswerText { get; set; }
        public bool IsAnswer { get; set; }
        public Nullable<bool> IsAnswerLastMarked { get; set; }
        public double Score { get; set; }
        public Nullable<double> ScoreLastMarked { get; set; }
        public Nullable<int> OptionOrder { get; set; }
        public string Feedback { get; set; }
    
        public virtual QZQuestion QZQuestion { get; set; }
    }
}
