//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QZQuiz
    {
        public QZQuiz()
        {
            this.QZResult = new HashSet<QZResult>();
            this.QZVideoQuizAttachement = new HashSet<QZVideoQuizAttachement>();
        }
    
        public int ID { get; set; }
        public int ThemeID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public string Title { get; set; }
        public string Note { get; set; }
        public Nullable<double> Passing { get; set; }
        public string Link { get; set; }
        public Nullable<double> TimeLimit { get; set; }
        public string Password { get; set; }
        public System.Guid CreatorPUID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> ModifyByPUID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public int AnswerReportMode { get; set; }
        public int DetailReportMode { get; set; }
        public int DisplayMode { get; set; }
        public int OptionType { get; set; }
        public bool Enabled { get; set; }
        public bool SectionRandomEnabled { get; set; }
        public bool QuestionRandomEnabled { get; set; }
        public bool ChoiceRandomEnabled { get; set; }
        public bool HideSection { get; set; }
        public bool SubmitOnly { get; set; }
        public bool SaveResponse { get; set; }
        public Nullable<bool> IsOtas { get; set; }
        public Nullable<int> OtasDocumentDisplayMode { get; set; }
        public Nullable<int> OtasOptionDisplayMode { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public Nullable<int> Attempts { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> IsSIO { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<bool> IsSchema { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string HLConfi { get; set; }
        public Nullable<System.DateTime> rptShowDate { get; set; }
        public Nullable<int> TestMode { get; set; }
        public bool EmailAuthor { get; set; }
        public bool RetakeQuiz { get; set; }
        public Nullable<bool> IsSkillset { get; set; }
    
        public virtual ICollection<QZResult> QZResult { get; set; }
        public virtual ICollection<QZVideoQuizAttachement> QZVideoQuizAttachement { get; set; }
    }
}
