//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QZVideoQuizQuePoint
    {
        public int ID { get; set; }
        public int QuizID { get; set; }
        public int QuestionID { get; set; }
        public int QuePoint { get; set; }
    
        public virtual QZQuestion QZQuestion { get; set; }
    }
}
